language: node_js

node_js:
  - 6

before_install:
  - sudo apt-get install make g++ python -y
  
install:
  - npm install node-gyp -g
  
before_script:
  - sudo npm install node-gyp -g

script:
  - npm start

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
    
services:
  mongodb
